name: build

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    security:
        name: Security
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
                os: [ ubuntu-latest ]
        steps:
            - name: Set Git To Use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
            - name: Update Composer
              run: composer self-update
            - name: Validate Composer Config
              run: composer validate
            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Restore Composer Cache
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-
            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                  timeout_minutes: 5
                  max_attempts: 5
                  command: composer update --prefer-dist --no-interaction --no-progress
            - name: Security Advisories
              run: composer require --dev roave/security-advisories:dev-latest

    psalm:
        name: Psalm
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
                os: [ ubuntu-latest ]
        steps:
            - name: Set Git To Use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
            - name: Update Composer
              run: composer self-update
            - name: Validate Composer Config
              run: composer validate
            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Restore Composer Cache
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-
            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                  timeout_minutes: 5
                  max_attempts: 5
                  command: composer update --prefer-dist --no-interaction --no-progress
            - name: Static Analysis
              continue-on-error: true
              run: vendor/bin/psalm --no-cache

    unit-tests:
        name: Build (${{matrix.php}}, ${{ matrix.os }}, ${{ matrix.stability }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2' ]
                os: [ ubuntu-latest, macos-latest, windows-latest ]
                stability: [ prefer-lowest, prefer-stable ]
        steps:
            - name: Set Git To Use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov
                  tools: pecl
                  ini-values: "memory_limit=-1"
                  extensions: phar, ffi
            - name: Update Composer
              run: composer self-update
            - name: Validate Composer Config
              run: composer validate
            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Restore Composer Cache
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-
            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                  timeout_minutes: 5
                  max_attempts: 5
                  command: composer update --${{ matrix.stability }} --ignore-platform-reqs --prefer-dist --no-interaction --no-progress
            - name: Install Linux SDL2
              if: runner.os == 'Linux'
              run: sudo apt-get install -y libsdl2-2.0-0
            - name: Install MacOS SDL2
              if: runner.os == 'macOS'
              run: brew install sdl2
            - name: Execute Tests
              run: vendor/bin/phpunit --testdox --verbose
