name: security

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  security:
    name: Security
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2' ]
        os: [ ubuntu-latest ]
    steps:
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Validate Composer
        run: composer validate
      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress
      - name: Composer Audit
        run: composer audit
      - name: Security Advisories
        run: composer require --dev roave/security-advisories:dev-latest
